# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 581160ad6a41e6065eb2e761309af8605d82b392623b657b6b075b02200de82b11429782f16f9617d34d34319281ba0d0c924306da90dbbfea9080d9d7e9b880

test:
  secret_key_base: eabe06733065d5c7ba7d9625bdd3e11251d88448981407cdb12edc000ce129f90abdec658e2273cbc0d1ecc6aa071396fabbbee39846fe5c50c16e5ecd79df69

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
